// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtmhffJ-MB9zVuIjyrkpNfav--aFMaoAw',
    appId: '1:878688860988:web:cd79e9971f1a89b7e6fc39',
    messagingSenderId: '878688860988',
    projectId: 'srocksmusicapp',
    authDomain: 'srocksmusicapp.firebaseapp.com',
    storageBucket: 'srocksmusicapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf2DT4w_9mxn275UfhTM7i-XUoLtDEdG0',
    appId: '1:878688860988:android:b3904ff339f52861e6fc39',
    messagingSenderId: '878688860988',
    projectId: 'srocksmusicapp',
    storageBucket: 'srocksmusicapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvpBbV75ojqogm4ylJrXPwC9GqtdQY3Gw',
    appId: '1:878688860988:ios:c940ac10dac88b9be6fc39',
    messagingSenderId: '878688860988',
    projectId: 'srocksmusicapp',
    storageBucket: 'srocksmusicapp.firebasestorage.app',
    iosBundleId: 'com.example.srocksmusicapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvpBbV75ojqogm4ylJrXPwC9GqtdQY3Gw',
    appId: '1:878688860988:ios:c940ac10dac88b9be6fc39',
    messagingSenderId: '878688860988',
    projectId: 'srocksmusicapp',
    storageBucket: 'srocksmusicapp.firebasestorage.app',
    iosBundleId: 'com.example.srocksmusicapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtmhffJ-MB9zVuIjyrkpNfav--aFMaoAw',
    appId: '1:878688860988:web:0322838ad9b7435ae6fc39',
    messagingSenderId: '878688860988',
    projectId: 'srocksmusicapp',
    authDomain: 'srocksmusicapp.firebaseapp.com',
    storageBucket: 'srocksmusicapp.firebasestorage.app',
  );

}